// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDahUxIQrZHBBZkUDkDUD30HBTd2aLwIs',
    appId: '1:1018196176066:web:11ddd95bc042f7ae081f5b',
    messagingSenderId: '1018196176066',
    projectId: 'justplanit-ebff7',
    authDomain: 'justplanit-ebff7.firebaseapp.com',
    databaseURL: 'https://justplanit-ebff7-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'justplanit-ebff7.appspot.com',
    measurementId: 'G-KLMMEMWJ47',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4073irroUrJYdYYi8GYr9NBMFmGGRocQ',
    appId: '1:1018196176066:android:a77e232c926de704081f5b',
    messagingSenderId: '1018196176066',
    projectId: 'justplanit-ebff7',
    databaseURL: 'https://justplanit-ebff7-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'justplanit-ebff7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjlrPjSxXkVZ9fIFg6z6L5EH6Hf0LkZdU',
    appId: '1:1018196176066:ios:25e28a1b4b45b756081f5b',
    messagingSenderId: '1018196176066',
    projectId: 'justplanit-ebff7',
    databaseURL: 'https://justplanit-ebff7-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'justplanit-ebff7.appspot.com',
    iosBundleId: 'com.just.planit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjlrPjSxXkVZ9fIFg6z6L5EH6Hf0LkZdU',
    appId: '1:1018196176066:ios:25e28a1b4b45b756081f5b',
    messagingSenderId: '1018196176066',
    projectId: 'justplanit-ebff7',
    databaseURL: 'https://justplanit-ebff7-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'justplanit-ebff7.appspot.com',
    iosBundleId: 'com.just.planit',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDDahUxIQrZHBBZkUDkDUD30HBTd2aLwIs',
    appId: '1:1018196176066:web:5d1bc0b35da15a24081f5b',
    messagingSenderId: '1018196176066',
    projectId: 'justplanit-ebff7',
    authDomain: 'justplanit-ebff7.firebaseapp.com',
    databaseURL: 'https://justplanit-ebff7-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'justplanit-ebff7.appspot.com',
    measurementId: 'G-6TJ4FV9D14',
  );

}